export const TEXT_DEF = {
  reedem: 'quả để ĐỔI LẤY',
  login: 'Tên đăng nhập',
  no_acc: 'Bạn chưa có tài khoản ? ',
  signup: 'Đăng ký ngay',
  account: 'Tài khoản',
  unconditional: 'không đủ điều kiện tham gia',
  not_exist: 'không tồn tại',
  network: 'Lỗi máy chủ',
  try_again: 'Vui lòng thử lại !!!',
  sum_seeded: 'Tổng đã thu hoạch:',
  sum_score: 'Tổng điểm đã nhận:',
  text_desc: 'Bỏ qua hướng dẫn',
  numWaterMelon: 'Số dưa hiện có',
  sell_le: 'Bán lẻ: ',
  sell_lo: 'Bán lô 12 quả: ',
  sell_vua: 'Bán vựa 30 quả: ',
  choose_num: 'Chọn số lượng muốn bán',
  rules: 'THỂ LỆ',
  rule1: '- Dành cho cấp VIP từ NEW-DIAMOND',
  rule2: '- Đăng nhập mỗi ngày để gieo hạt, tưới nước, thu hoạch quả',
  program: 'NỘI DUNG CHƯƠNG TRÌNH',
  programCt1:
    '- Có 4 thao tác trong game: Gieo Hạt, Tưới Nước & Thu Hoạch và Bán',
  programCt2:
    '+ Gieo Hạt: Mỗi ngày có thể gieo 1 Hạt mới, nếu được Tưới Nước mỗi ngày hạt sẽ nở ra Trái Dưa Hấu sau 7 ngày, nếu 1 ngày không được Tưới Nước hạt sẽ hỏng.',
  programCt3:
    '+ Tưới Nước: Có thể Tưới Nước mỗi ngày không giới hạn số hạt được tưới, mỗi hạt chỉ cần tưới 1 lần/ngày.',
  programCt4:
    '+ Thu Hoạch: Sau 7 ngày có thể Thu Hoạch quả, quả đã có mà không được Thu Hoạch sẽ hỏng sau 3 ngày.',
  programCt5:
    '+ Bán: Có thể bán 1 hoặc nhiều Trái Dưa Hấu 1 lúc để thu về mức điểm khác nhau.',
  text_sown_seed: 'Bạn đã gieo hạt hôm nay THÀNH CÔNG!',
  text_desc_sown_seed: 'Hãy chăm chỉ tưới nước HẰNG NGÀY nhé!',
  click_here: 'Nhấn vào đây',
  text_drills: '“Gieo hạt”',
  horizontal_pull: 'Kéo ngang',
  broken_tree: 'Cây hỏng',
  streed: 'Cây đã',
  water_plants: '“Tưới nước”',
  no_water_plants: '“do không tưới nước”',
  harvest: '“Thu hoạch”',
  successful_harvest: '“thu hoạch thành công”',
  fail_harvest: '“do không thu hoạch”',
  text_stree: 'Hạt đã nảy mầm',
  text_flower: 'Cây đã ra bông',
  message_water: 'Bạn đã tưới nước cho cây này THÀNH CÔNG!',
  message_broken_tree_water: 'CÂY HỎNG VÌ KHÔNG  TƯỚI NƯỚC THƯỞNG XUYÊN',
  message_broken_flower: 'BÔNG HỎNG VÌ KHÔNG TƯỚI NƯỚC THƯỞNG XUYÊN',
  message_harvested: 'Bạn đã thu hoạch được 1 trái dưa hấu',
  message_success: 'XIN CHÚC MỪNG!',
  message_fail: 'THU HOẠCH THẤT BẠI',
  message_harvested_s: 'ĐÃ THU HOẠCH!',
  sell: '“BÁN”',
  choose_quantity: '“CHỌN SỐ LƯỢNG”',
  sell_now: '“BÁN NGAY”',
  text_agree: '“ĐỒNG Ý”',
  maintenance:
    'Trò chơi đang được bảo trì. Vui lòng liên hệ chúng tôi để cần hỗ trợ cần thiết đến quý hội viên !',
  sellCF1: 'XIN CHÚC MỪNG',
  sellCF2: 'HÃY CHĂM CHỈ HƠN NHÉ !',
  message_drillsed: 'ĐÃ GIEO HẠT',
  store: '“KHO”',
  retail: 'Bán lẻ: 0.1 - 2Đ',
  sell_lots: 'Bán lô 12 quả: 15.0 - 25.0Đ',
  sell_barn: ' Bán vựa 30 quả: 55.0 - 65.0Đ',
  text_Tutorial: 'Bán lẻ 1 quả để đổi lấy',
  message_final_1: 'BẠN ĐÃ HOÀN TẤT HƯỚNG DẪN.',
  message_final_2: 'HÃY CHĂM CHÚT CHO ĐẢO DƯA CỦA MÌNH MỖI NGÀY NHÉ',
  LOGIN: 'ĐĂNG NHẬP',
  DONE: 'THÀNH CÔNG',
  WAITING: 'Quý khách vui lòng đợi: '
}

export const bannersConst = [
  '/images/banner1.png',
  '/images/banner2.png',
  '/images/banner3.png',
  '/images/banner4.png'
]
