
name: Node.js CI
on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn        
    - run: yarn build
      env:
          CI: ""
    - run: pm2 stop 6
    - run: pm2 start 6
    # - run: pm2 start "npm run dev" --name front-end
    - run: sudo service nginx stop
    - run: sudo service nginx restart
